# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEiFr02RXHtTV59Cvq8LMU0x5a2xZbIa
"""

checkerboard = [[0]*8 for _ in range(8)]

x1, y1 = map(int, input().split())
x2, y2 = map(int, input().split())
if (x1, y1) == (x2, y2):
    print('No')
elif x2 < 0 or x2 > 7 or y2 < 0 or y2 > 7 or checkerboard[x2][y2] == 1:
    print('No')
elif abs(x2 - x1) <= 1 and abs(y2 - y1) <= 1:
    print('Yes')
else:
    print('No')